### ISSUE TITLE
Grouping functionality

### ISSUE THREAD

**Issue by mistris** [200MPH/tnt#12]
@200MPH can you please give me an example of grouping functionality?
https://github.com/200MPH/tnt/blob/develop/docs/Shipping/howTo.md#7-group-functionality

**Comment by 200MPH** [comment]
Hello, sorry for late answer, too busy...
Is this something you still need a help with ?

**Comment by mistris** [comment]
Hello @200MPH!

It would be useful for everyone if you would post an example.

**Comment by 200MPH** [comment]
Will do when find free time.
TNT is now part of Fedex. 
Not so sure how long they will use this API.
