### ISSUE TITLE
non-ascii

### ISSUE THREAD

**Issue by simaojf** [200MPH/tnt#14]
Hello, Did you had any problem with non-ascii chars. The VB script smaple on TNT documentation transform any non-ascii to an HEX and they append it to the rest of the string with an % before. But for me is not working.

**Comment by 200MPH** [comment]
Hello, sorry for late answer.
You are the first who experiencing this kind of issue.
Unfortunately I'm too busy to have a look in to it now, but when find some time I will.
Feel free to contribute if you want to :)

**Comment by simaojf** [comment]
Hi. Thanks for the reply.
Don't worry, my question wasn't related to this project. I had to do a similar project in python, and  my problem was in the uft-8 encode. I found out that TNT uses a Windows-1252 encoding, not the ISO. This is an old encoding issue: https://www.i18nqa.com/debug/bug-iso8859-1-vs-windows-1252.html
In python my solution was to encode the message using:  the_message.encode('cp1252')
Thanks,
