### ISSUE TITLE
need some help

### ISSUE THREAD

**Issue by abu-cwarky** [200MPH/tnt#20]
Hello. I need to send a shipment request for someone and pay with my account.
According to documentation if  :

"A PAYMENTIND type of “S” represents a sender pays shipments, “R” represents a receiver. If this element is not supplied, then the payment type is defaulted to sender.
Within ExpressConnect shipping there is limited support for ‘Receiver pays’ shipments. In order to create a receiver pays shipment you must first register the following details with TNT:
1. The <ACCOUNT> and <ACCOUNTCOUNTRY> combinations that you would like activated for receiver pays. This need to be added to our database and associated with your userid and password before receiver pays is activate for these accounts. The TNT representative will arrange this.
Once the above details have been registered, simply amend the following in the INPUT XML to send a receiver pays shipment:
i. Within the DETAILS parent element set the <PAYMENTIND> field to ‘R’:
<PAYMENTIND>R</PAYMENTIND>
ii. Within the SENDER parent element enter the sender’s account in the <ACCOUNT> field:
<ACCOUNT>111</ACCOUNT>
iii. Within the RECEIVER parent element add 2 additional tags for the receiver’s account and account country:
\<RECEIVER\>
\<COMPANYNAME\>Receivers Co. Ltd.\</COMPANYNAME\>
\<STREETADDRESS1\>Head Office \</STREETADDRESS1\>
\<STREETADDRESS2\>Hoofddorp\</STREETADDRESS2\>
\<STREETADDRESS3\>\</STREETADDRESS3\>
\<CITY\>Amsterdam\</CITY\>
\<PROVINCE\>\</PROVINCE\>
\<POSTCODE\>1100 KG\</POSTCODE\>
\<COUNTRY\>NL\</COUNTRY\>
\<VAT\>\</VAT\>
\<CONTACTNAME\>Mr Frank\</CONTACTNAME\>
\<CONTACTDIALCODE\>39 203\</CONTACTDIALCODE\>
\<CONTACTTELEPHONE\>987432\</CONTACTTELEPHONE\>
\<CONTACTEMAIL\>FrankA@rec.com\</CONTACTEMAIL\>
\<ACCOUNT\>123\</ACCOUNT\>
\<ACCOUNTCOUNTRY\>NL\</ACCOUNTCOUNTRY\>
\</RECEIVER>
"

If i put 
"$c1->setReceiver()->setCompanyName('xxx')
                  ->setAddressLine('xxx')
                  ->setAddressLine('xxx')
                  ->setCity('xxx')
                  ->setPostcode('000')
                  ->setCountry('xx')
                  ->setContactName('xxx')
                  ->setContactDialCode('xxx')
                  ->setContactPhone('xxx')
                  ->setContactEmail('xxx')
                  ->setAccountNumber('000000000')
                  ->setAcountCountry('xx');"
in xml there is no account and accountcountry. Could you give me a hint? Thanks for your time.

**Comment by 200MPH** [comment]
Checking now... I will come back to you ASAP

**Comment by 200MPH** [comment]
All sorted.
Please update to 3.0.7

Thank you for reporting this issue.
