### ISSUE TITLE
Incorect request XML - duplicate elements

### ISSUE THREAD

**Issue by abu-cwarky** [200MPH/tnt#22]
Hello again. Thanks for taking care of account and accountcountry nodes but there is a new issue. 
Collecctionaddress, details, receiver and delivery nodes are now tripled in generated XML. Thanks again for your time and effort.

**Comment by 200MPH** [comment]
Please paste your code

**Comment by abu-cwarky** [comment]
Ok, This is the request:

`require_once("lib/tnt/vendor/autoload.php");

use thm\tnt_ec\service\ShippingService\ShippingService;

$shipping = new ShippingService('xxx', 'xxx');

$shipping->disableSSLVerify();
$shipping->setAccountNumber('123456789') // will be provided by your TNT representative.
         ->createOptionalActivities() // this will generate <ACTIVITY> optional elements automatically.
         ->setSender()->setCompanyName('xxx')
                      ->setAddressLine('xxx')
                      ->setCity('xxx')
                      ->setPostcode('33990')
                      ->setCountry('FR')
                      ->setContactName('xxx')
                      ->setContactDialCode('0000')
                      ->setContactPhone('000000')
                      ->setContactEmail('xxx@example.com');

$date_ = date("d/m/Y", strtotime("tomorrow"));

$shipping->setCollection()->useSenderAddress() // use same addres as is for sender
                          ->setShipDate($date_) // ('19/01/2018')
                          ->setPrefCollectTime('10:00', '12:00')
                          ->setCollectInstruction('');

$c1 = $shipping->addConsignment()->setConReference('000000000')
                                 ->setCustomerRef('xxx')
                                 ->setContype('N')
                                 ->setPaymentind('R')
                                 ->setItems(1)
                                 ->setTotalWeight(5)
                                 ->setTotalVolume(0.002)
                                 ->setService('15N') // will be provided by your TNT representative.
                                 ->setDescription('---')
                                 ->setDeliveryInstructions('---');

$c1->setReceiver()->setCompanyName('xxx')
                  ->setAddressLine('xxx')
                  ->setAddressLine('xxx')
                  ->setCity('xxx')
                  ->setPostcode('000000')
                  ->setCountry('xx')
                  ->setContactName('xxx')
                  ->setContactDialCode('0000')
                  ->setContactPhone('0000000000')
                  ->setContactEmail('xxx')
                  ->setAccountNumber('123456789')
                  ->setAcountCountry('xx');


$c1->setReceiverAsDelivery(); // make delivery address same as receiver

$c1->addPackage()->setItems(1)
                 ->setDescription('xxx')
                 ->setLength(0.18)
                 ->setHeight(0.05)
                 ->setWidth(0.10)
                 ->setWeight(0.5);
//print_r($shipping);
//print_r($shipping->getXmlContent());

$response = $shipping->send();`

and here is the according xml that I got : 
`<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<ESHIPPER>
    <LOGIN>
        <COMPANY>xxx</COMPANY>
        <PASSWORD>xxx</PASSWORD>
        <APPID>IN</APPID>
        <APPVERSION>3.0</APPVERSION>
    </LOGIN>
    <CONSIGNMENTBATCH>
        <SENDER>
            <ACCOUNT><![CDATA[123456789]]></ACCOUNT>
            <COMPANYNAME><![CDATA[xxx]]></COMPANYNAME>
            <STREETADDRESS1><![CDATA[xxx]]></STREETADDRESS1>
            <CITY><![CDATA[xxx]]></CITY>
            <POSTCODE><![CDATA[33990]]></POSTCODE>
            <COUNTRY><![CDATA[FR]]></COUNTRY>
            <ACCOUNT><![CDATA[123456789]]></ACCOUNT>
            <CONTACTNAME><![CDATA[xxx]]></CONTACTNAME>
            <CONTACTDIALCODE><![CDATA[0000]]></CONTACTDIALCODE>
            <CONTACTTELEPHONE><![CDATA[000000]]></CONTACTTELEPHONE>
            <CONTACTEMAIL><![CDATA[xxx@example.com]]></CONTACTEMAIL>
            <COLLECTION>
                <COLLECTIONADDRESS>
                    <COMPANYNAME><![CDATA[xxx]]></COMPANYNAME>
                    <STREETADDRESS1><![CDATA[xxx]]></STREETADDRESS1>
                    <CITY><![CDATA[xxx]]></CITY>
                    <POSTCODE><![CDATA[33990]]></POSTCODE>
                    <COUNTRY><![CDATA[FR]]></COUNTRY>
                    <CONTACTNAME><![CDATA[xxx]]></CONTACTNAME>
                    <CONTACTDIALCODE><![CDATA[0000]]></CONTACTDIALCODE>
                    <CONTACTTELEPHONE><![CDATA[000000]]></CONTACTTELEPHONE>
                    <CONTACTEMAIL><![CDATA[xxx@example.com]]></CONTACTEMAIL>
                </COLLECTIONADDRESS>
                <COLLECTIONADDRESS>
                    <COMPANYNAME><![CDATA[xxx]]></COMPANYNAME>
                    <STREETADDRESS1><![CDATA[xxx]]></STREETADDRESS1>
                    <CITY><![CDATA[xxx]]></CITY>
                    <POSTCODE><![CDATA[33990]]></POSTCODE>
                    <COUNTRY><![CDATA[FR]]></COUNTRY>
                    <CONTACTNAME><![CDATA[xxx]]></CONTACTNAME>
                    <CONTACTDIALCODE><![CDATA[0000]]></CONTACTDIALCODE>
                    <CONTACTTELEPHONE><![CDATA[000000]]></CONTACTTELEPHONE>
                    <CONTACTEMAIL><![CDATA[xxx@example.com]]></CONTACTEMAIL>
                </COLLECTIONADDRESS>
                <COLLECTIONADDRESS>
                    <COMPANYNAME><![CDATA[xxx]]></COMPANYNAME>
                    <STREETADDRESS1><![CDATA[xxx]]></STREETADDRESS1>
                    <CITY><![CDATA[xxx]]></CITY>
                    <POSTCODE><![CDATA[33990]]></POSTCODE>
                    <COUNTRY><![CDATA[FR]]></COUNTRY>
                    <CONTACTNAME><![CDATA[xxx]]></CONTACTNAME>
                    <CONTACTDIALCODE><![CDATA[0000]]></CONTACTDIALCODE>
                    <CONTACTTELEPHONE><![CDATA[000000]]></CONTACTTELEPHONE>
                    <CONTACTEMAIL><![CDATA[xxx@example.com]]></CONTACTEMAIL>
                </COLLECTIONADDRESS>
                <SHIPDATE><![CDATA[06/05/2020]]></SHIPDATE>
                <PREFCOLLECTTIME>
                    <FROM><![CDATA[10:00]]></FROM>
                    <TO><![CDATA[12:00]]></TO>
                </PREFCOLLECTTIME>
                <COLLINSTRUCTIONS><![CDATA[]]></COLLINSTRUCTIONS>
            </COLLECTION>
        </SENDER>
        <CONSIGNMENT>
            <CONREF>000000000</CONREF>
            <DETAILS>
                <RECEIVER>
                    <COMPANYNAME><![CDATA[xxx]]></COMPANYNAME>
                    <STREETADDRESS1><![CDATA[xxx]]></STREETADDRESS1>
                    <STREETADDRESS2><![CDATA[xxx]]></STREETADDRESS2>
                    <CITY><![CDATA[xxx]]></CITY>
                    <POSTCODE><![CDATA[000000]]></POSTCODE>
                    <COUNTRY><![CDATA[xx]]></COUNTRY>
                    <CONTACTNAME><![CDATA[xxx]]></CONTACTNAME>
                    <CONTACTDIALCODE><![CDATA[0000]]></CONTACTDIALCODE>
                    <CONTACTTELEPHONE><![CDATA[0000000000]]></CONTACTTELEPHONE>
                    <CONTACTEMAIL><![CDATA[xxx]]></CONTACTEMAIL>
                    <ACCOUNT><![CDATA[123456789]]></ACCOUNT>
                    <ACCOUNTCOUNTRY><![CDATA[xx]]></ACCOUNTCOUNTRY>
                </RECEIVER>
                <DELIVERY>
                    <COMPANYNAME><![CDATA[xxx]]></COMPANYNAME>
                    <STREETADDRESS1><![CDATA[xxx]]></STREETADDRESS1>
                    <STREETADDRESS2><![CDATA[xxx]]></STREETADDRESS2>
                    <CITY><![CDATA[xxx]]></CITY>
                    <POSTCODE><![CDATA[000000]]></POSTCODE>
                    <COUNTRY><![CDATA[xx]]></COUNTRY>
                    <CONTACTNAME><![CDATA[xxx]]></CONTACTNAME>
                    <CONTACTDIALCODE><![CDATA[0000]]></CONTACTDIALCODE>
                    <CONTACTTELEPHONE><![CDATA[0000000000]]></CONTACTTELEPHONE>
                    <CONTACTEMAIL><![CDATA[xxx]]></CONTACTEMAIL>
                    <ACCOUNT><![CDATA[123456789]]></ACCOUNT>
                    <ACCOUNTCOUNTRY><![CDATA[xx]]></ACCOUNTCOUNTRY>
                </DELIVERY>
                <CONREF>000000000</CONREF>
                <DETAILS>
                    <RECEIVER>
                        <COMPANYNAME><![CDATA[xxx]]></COMPANYNAME>
                        <STREETADDRESS1><![CDATA[xxx]]></STREETADDRESS1>
                        <STREETADDRESS2><![CDATA[xxx]]></STREETADDRESS2>
                        <CITY><![CDATA[xxx]]></CITY>
                        <POSTCODE><![CDATA[000000]]></POSTCODE>
                        <COUNTRY><![CDATA[xx]]></COUNTRY>
                        <CONTACTNAME><![CDATA[xxx]]></CONTACTNAME>
                        <CONTACTDIALCODE><![CDATA[0000]]></CONTACTDIALCODE>
                        <CONTACTTELEPHONE><![CDATA[0000000000]]></CONTACTTELEPHONE>
                        <CONTACTEMAIL><![CDATA[xxx]]></CONTACTEMAIL>
                        <ACCOUNT><![CDATA[123456789]]></ACCOUNT>
                        <ACCOUNTCOUNTRY><![CDATA[xx]]></ACCOUNTCOUNTRY>
                    </RECEIVER>
                    <DELIVERY>
                        <COMPANYNAME><![CDATA[xxx]]></COMPANYNAME>
                        <STREETADDRESS1><![CDATA[xxx]]></STREETADDRESS1>
                        <STREETADDRESS2><![CDATA[xxx]]></STREETADDRESS2>
                        <CITY><![CDATA[xxx]]></CITY>
                        <POSTCODE><![CDATA[000000]]></POSTCODE>
                        <COUNTRY><![CDATA[xx]]></COUNTRY>
                        <CONTACTNAME><![CDATA[xxx]]></CONTACTNAME>
                        <CONTACTDIALCODE><![CDATA[0000]]></CONTACTDIALCODE>
                        <CONTACTTELEPHONE><![CDATA[0000000000]]></CONTACTTELEPHONE>
                        <CONTACTEMAIL><![CDATA[xxx]]></CONTACTEMAIL>
                        <ACCOUNT><![CDATA[123456789]]></ACCOUNT>
                        <ACCOUNTCOUNTRY><![CDATA[xx]]></ACCOUNTCOUNTRY>
                    </DELIVERY>
                    <CONREF>000000000</CONREF>
                    <DETAILS>
                        <RECEIVER>
                            <COMPANYNAME><![CDATA[xxx]]></COMPANYNAME>
                            <STREETADDRESS1><![CDATA[xxx]]></STREETADDRESS1>
                            <STREETADDRESS2><![CDATA[xxx]]></STREETADDRESS2>
                            <CITY><![CDATA[xxx]]></CITY>
                            <POSTCODE><![CDATA[000000]]></POSTCODE>
                            <COUNTRY><![CDATA[xx]]></COUNTRY>
                            <CONTACTNAME><![CDATA[xxx]]></CONTACTNAME>
                            <CONTACTDIALCODE><![CDATA[0000]]></CONTACTDIALCODE>
                            <CONTACTTELEPHONE><![CDATA[0000000000]]></CONTACTTELEPHONE>
                            <CONTACTEMAIL><![CDATA[xxx]]></CONTACTEMAIL>
                            <ACCOUNT><![CDATA[123456789]]></ACCOUNT>
                            <ACCOUNTCOUNTRY><![CDATA[xx]]></ACCOUNTCOUNTRY>
                        </RECEIVER>
                        <DELIVERY>
                            <COMPANYNAME><![CDATA[xxx]]></COMPANYNAME>
                            <STREETADDRESS1><![CDATA[xxx]]></STREETADDRESS1>
                            <STREETADDRESS2><![CDATA[xxx]]></STREETADDRESS2>
                            <CITY><![CDATA[xxx]]></CITY>
                            <POSTCODE><![CDATA[000000]]></POSTCODE>
                            <COUNTRY><![CDATA[xx]]></COUNTRY>
                            <CONTACTNAME><![CDATA[xxx]]></CONTACTNAME>
                            <CONTACTDIALCODE><![CDATA[0000]]></CONTACTDIALCODE>
                            <CONTACTTELEPHONE><![CDATA[0000000000]]></CONTACTTELEPHONE>
                            <CONTACTEMAIL><![CDATA[xxx]]></CONTACTEMAIL>
                            <ACCOUNT><![CDATA[123456789]]></ACCOUNT>
                            <ACCOUNTCOUNTRY><![CDATA[xx]]></ACCOUNTCOUNTRY>
                        </DELIVERY>
                        <CUSTOMERREF><![CDATA[xxx]]></CUSTOMERREF>
                        <CONTYPE><![CDATA[N]]></CONTYPE>
                        <PAYMENTIND><![CDATA[R]]></PAYMENTIND>
                        <ITEMS><![CDATA[1]]></ITEMS>
                        <TOTALWEIGHT><![CDATA[5]]></TOTALWEIGHT>
                        <TOTALVOLUME><![CDATA[0.002]]></TOTALVOLUME>
                        <SERVICE><![CDATA[15N]]></SERVICE>
                        <DESCRIPTION><![CDATA[---]]></DESCRIPTION>
                        <DELIVERYINST><![CDATA[---]]></DELIVERYINST>
                        <PACKAGE>
                            <ITEMS><![CDATA[1]]></ITEMS>
                            <DESCRIPTION><![CDATA[xxx]]></DESCRIPTION>
                            <LENGTH><![CDATA[0.18]]></LENGTH>
                            <HEIGHT><![CDATA[0.05]]></HEIGHT>
                            <WIDTH><![CDATA[0.1]]></WIDTH>
                            <WEIGHT><![CDATA[0.5]]></WEIGHT>
                        </PACKAGE>
                    </DETAILS>
                    <PACKAGE>
                        <ITEMS><![CDATA[1]]></ITEMS>
                        <DESCRIPTION><![CDATA[xxx]]></DESCRIPTION>
                        <LENGTH><![CDATA[0.18]]></LENGTH>
                        <HEIGHT><![CDATA[0.05]]></HEIGHT>
                        <WIDTH><![CDATA[0.1]]></WIDTH>
                        <WEIGHT><![CDATA[0.5]]></WEIGHT>
                    </PACKAGE>
                </DETAILS>
                <PACKAGE>
                    <ITEMS><![CDATA[1]]></ITEMS>
                    <DESCRIPTION><![CDATA[xxx]]></DESCRIPTION>
                    <LENGTH><![CDATA[0.18]]></LENGTH>
                    <HEIGHT><![CDATA[0.05]]></HEIGHT>
                    <WIDTH><![CDATA[0.1]]></WIDTH>
                    <WEIGHT><![CDATA[0.5]]></WEIGHT>
                </PACKAGE>
            </DETAILS>
        </CONSIGNMENT>
    </CONSIGNMENTBATCH>
    <ACTIVITY>
        <CREATE>
            <CONREF><![CDATA[000000000]]></CONREF>
        </CREATE>
        <BOOK ShowBookingRef="Y">
            <CONREF><![CDATA[000000000]]></CONREF>
        </BOOK>
        <SHIP>
            <CONREF><![CDATA[000000000]]></CONREF>
        </SHIP>
        <PRINT>
            <REQUIRED>
                <CONREF><![CDATA[000000000]]></CONREF>
            </REQUIRED>
        </PRINT>
        <SHOW_GROUPCODE />
    </ACTIVITY>
</ESHIPPER>`

**Comment by 200MPH** [comment]
OK

I would not worry about it :)
The duplicates are generated after request is sent to the carrier.
So carrier got a valid XML request.
When you uncomment line
`//print_r($shipping->getXmlContent());`
you won't get duplicates and the same string is transfer to the carrier API.

I will keep this issue open till I fix it, as it may confuse others.
It seems to be an old issue, not related to the recent fix.

Good luck !

**Comment by abu-cwarky** [comment]
There is also another problem. At SENDER node ACCOUNT node is also twice. One at the top and one where it should be and I get an error :
"Invalid content was found starting with element 'ACCOUNT'. One of '{COMPANYNAME}' is expected."

**Comment by abu-cwarky** [comment]
I just made some tests and to make all work for receiver to pay there are 2 more things :
1. In SENDER node ACCOUNT node MUST be present and empty if receiver pays : `<ACCOUNT><![CDATA[]]></ACCOUNT>`
3. No ACCOUNT and ACCOUNTCOUNTRY nodes should be in DELIVERY if setReceiverAsDelivery() is used

**Comment by 200MPH** [comment]
Have not notice ACCOUNT problem during testing...
Will deploy another fix soon

**Comment by 200MPH** [comment]
Please update :)
