### ISSUE TITLE
Incorect XML if receiver pays

### ISSUE THREAD

**Issue by abu-cwarky** [200MPH/tnt#25]
There is one issue not solved.
If I use : $shipping->setAccountNumber('') or not specified at all I get the following error:
"Invalid content was found starting with element 'CONTACTNAME'. One of '{ACCOUNT}' is expected. "
In case of receiver pays "<ACCOUNT></ACCOUNT>" works. Node must be there empty. I know it's stupid but it's TNT :)
Thanks again for your effort.

**Comment by 200MPH** [comment]
Right... now it's OK :)

**Comment by abu-cwarky** [comment]
I confirm. Everything is ok now. Thanks

**Comment by 200MPH** [comment]
Please give a star if you like it :)

**Comment by abu-cwarky** [comment]
Done. Of course I like it because I use it :) You're a great guy also :)

**Comment by 200MPH** [comment]
Thank you!
