### ISSUE TITLE
Erreur message

### ISSUE THREAD

**Issue by robinsaillard** [200MPH/tnt#28]
@200MPH can you please help me ? 
 I get the error message :  "cvc-complex-type.2.4.a: Invalid content was found starting with element 'CONTACTTELEPHONE'. One of '{CONTACTDIALCODE}' is expected.1719 [requestXml:thm\tnt_ec\service\AbstractResponse:private] "

**Comment by 200MPH** [comment]
What did you put into CONTACTDIALCODE?
It must be country dial code like +48 or 0048
