### ISSUE TITLE
Save  response as PDF

### ISSUE THREAD

**Issue by DPlachkov** [200MPH/tnt#29]
How do you save the response as PDF. I have found the HTML xsl files but they do not work when trying to save them as a pdf. I've seen a post from 2018 saying this is a work in progress. Is there a way to persist the response directly to a pdf, or is there some XSL stylesheet available to load with the xml to persist the label as PDF

**Comment by 200MPH** [comment]
Due to lack of time and unknow future of TNT API (now Fedex) I won't develope this feature. 
Maybe some time, who knows ...
