### ISSUE TITLE
Error on COLLECTIONADDRESS - SHIPDATE

### ISSUE THREAD

**Issue by alessandrodallavia** [200MPH/tnt#31]
Hi, I am inexperienced but I have been trying to install and use this package for some time. The error is: ... Invalid content was found starting with element 'COLLECTIONADDRESS'. One of '{SHIPDATE}' is expected.3320 [requestXml:thm\tnt_ec\service\AbstractResponse:private] => GET_RESULT:...... . What should I do to fix?

Please help me. Thanks in advance.

**Comment by karolzlot** [comment]
Probably not worth it as Fedex is transferring TNT clients to Fedex. In Poland migration is already over (it happened in July 2021), so I don't know where are you from but it will probably happen soon.

**Comment by alessandrodallavia** [comment]
Hi @karolzlot, thank you for your answer. I come from Italy and it is the first time that I commit myself to additions of this type. Can I ask you if you have already integrated TNT / Fedex into your systems?

I am looking for help, as I have developed, according to the TNT guides, the XML file and the call to their systems. It seems to work, but I believe the label it returns to me is incorrect.

Thanks for all.

**Comment by 200MPH** [comment]
TNT belongs to Fedex now. However we still using TNT API. Not sure for how long ...
Have you prepare your request as below? 

```
$shipping = new ShippingService('User ID', 'Password');

$shipping->setAccountNumber('') // will be provided by your TNT representative.
         ->createOptionalActivities() // this will generate <ACTIVITY> optional elements automatically.
         ->setSender()->setCompanyName('')
                      ->setAddressLine('')
                      ->setCity('')
                      ->setPostcode('')
                      ->setCountry('')
                      ->setContactName('')
                      ->setContactDialCode('')
                      ->setContactPhone('')
                      ->setContactEmail('');

$shipping->setCollection()->useSenderAddress() // use same addres as is for sender
                          ->setShipDate('19/01/2018')
                          ->setPrefCollectTime('10:00', '12:00')
                          ->setCollectInstruction('');

$c1 = $shipping->addConsignment()->setConReference('')
                                 ->setCustomerRef('')
                                 ->setContype('N')
                                 ->setPaymentind('S')
                                 ->setItems(0)
                                 ->setTotalWeight(0)
                                 ->setTotalVolume(0.00)
                                 ->setService('15N') // will be provided by your TNT representative.
                                 ->setDescription('')
                                 ->setDeliveryInstructions('');

$c1->setReceiver()->setCompanyName('')
                  ->setAddressLine('')
                  ->setAddressLine('')
                  ->setCity('')
                  ->setPostcode('')
                  ->setCountry('')
                  ->setContactName('')
                  ->setContactDialCode('')
                  ->setContactPhone('')
                  ->setContactEmail('');

$c1->useReceiverAddressForDelivery();
```

**Comment by alessandrodallavia** [comment]
Sorry for the delay. Yes I prepared the request as yours.

**Comment by 200MPH** [comment]
It's been a while but please make sure setShipDate() date parameter is in format DD/MM/YYYY and it's not past.
