### ISSUE TITLE
"Private methods cannot be final" in PHP8

### ISSUE THREAD

**Issue by SkyportDEV** [200MPH/tnt#33]
Hi,

in PHP8 I will get the following error:
Warning: Private methods cannot be final as they are never overridden by other classes in ../vendor/200mph/tnt-express-connect/src/service/ShippingService/ShippingService.php on line 343

**Comment by 200MPH** [comment]
Thanks for reporting this.
Final private does not makes a sense so I will modify it.
For now please leave with warnings :)

**Comment by SkyportDEV** [comment]
The problem is, that this warning is showing in PHP8.2, even warnings are disabled. It's not useful if you want plain JSON output.
