### ISSUE TITLE
AbstractXml destructor emiting a warning

### ISSUE THREAD

**Issue by mariopereiraBnext** [200MPH/tnt#34]
With every send, I got the following error:

`XMLWriter::flush(): Invalid or uninitialized XMLWriter object at vendor\200mph\tnt-express-connect\src\service\ShippingService\entity\AbstractXml.php (39)`

I'm afraid that commenting the flush may leave some processing to do.
What is the best solution for this?

**Comment by 200MPH** [comment]
What if you replace the line 39 to something like this:

`if($this->xml instanceof XmlWriter) {
    $this->xml->flush();
}
`
This is untested code. Please do on you local environemnt and let me know whether it work now, so I will merge it.

**Comment by mariopereiraBnext** [comment]
Yes, that works. No more warnings. Please merge it, and I'll do a composer update
Thanks

**Comment by 200MPH** [comment]
Your change won't affect anything so you can keep it as is
