### ISSUE TITLE
Tnt Label generate with getting errors

### ISSUE THREAD

**Issue by Chirag-Prajapati** [200MPH/tnt#5]
Hi,
I am using your package for TNT label generate but I am getting the below error when sending the request. 
Array ( [PRINT] => Array ( [CONNOTE] => N [LABEL] => N [MANIFEST] => N [INVOICE] => N ) )
So can you help me?

**Comment by 200MPH** [comment]
Hello,

Could you paste output from $response->getErrors () and also paste your XML request using $shipping->getXmlContent().

Regards,
Wojtek


From: Chirag
Sent: 03 July 2018 12:26
To: 200MPH/tnt
Cc: Subscribed
Subject: [200MPH/tnt] Tnt Label generate with getting errors (#5)

,
I have used your package for TNT label generate but I am getting the below error when sending the request.
Array ( [PRINT] => Array ( [CONNOTE] => N [LABEL] => N [MANIFEST] => N [INVOICE] => N ) )
So can you help me?

**Comment by Chirag-Prajapati** [comment]
I have printed the output of $response->getErrors() and it is blank.
Below is output of $shipping->getXmlContent():
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<ESHIPPER>
 <LOGIN>
  <COMPANY>Cd1@te</COMPANY>
  <PASSWORD>Cd1@te123</PASSWORD>
  <APPID>EC</APPID>
  <APPVERSION>3.0</APPVERSION>
 </LOGIN>
 <CONSIGNMENTBATCH>
  <SENDER><COMPANYNAME><![CDATA[ErinCondren.Com]]></COMPANYNAME>
<STREETADDRESS1><![CDATA[201 W Howard Lane]]></STREETADDRESS1>
<CITY><![CDATA[Austin]]></CITY>
<PROVINCE><![CDATA[Province]]></PROVINCE>
<POSTCODE><![CDATA[78753]]></POSTCODE>
<COUNTRY><![CDATA[US]]></COUNTRY>
<ACCOUNT><![CDATA[70365588]]></ACCOUNT>
<VAT><![CDATA[123123]]></VAT>
<CONTACTNAME><![CDATA[Aren]]></CONTACTNAME>
<CONTACTDIALCODE><![CDATA[Dial code]]></CONTACTDIALCODE>
<CONTACTTELEPHONE><![CDATA[Contact phone]]></CONTACTTELEPHONE>
<CONTACTEMAIL><![CDATA[Email]]></CONTACTEMAIL>
   <COLLECTION><COLLECTIONADDRESS><COMPANYNAME><![CDATA[ErinCondren.Com]]></COMPANYNAME>
<STREETADDRESS1><![CDATA[201 W Howard Lane]]></STREETADDRESS1>
<CITY><![CDATA[Austin]]></CITY>
<PROVINCE><![CDATA[Province]]></PROVINCE>
<POSTCODE><![CDATA[78753]]></POSTCODE>
<COUNTRY><![CDATA[US]]></COUNTRY>

<VAT><![CDATA[123123]]></VAT>
<CONTACTNAME><![CDATA[Aren]]></CONTACTNAME>
<CONTACTDIALCODE><![CDATA[Dial code]]></CONTACTDIALCODE>
<CONTACTTELEPHONE><![CDATA[Contact phone]]></CONTACTTELEPHONE>
<CONTACTEMAIL><![CDATA[Email]]></CONTACTEMAIL>
</COLLECTIONADDRESS>
<SHIPDATE><![CDATA[16/01/2018]]></SHIPDATE>
<PREFCOLLECTTIME>
 <FROM><![CDATA[10:00]]></FROM>
 <TO><![CDATA[12:00]]></TO>
</PREFCOLLECTTIME>
<ALTCOLLECTTIME>
 <FROM><![CDATA[12:00]]></FROM>
 <TO><![CDATA[14:00]]></TO>
</ALTCOLLECTTIME>
<COLLINSTRUCTIONS><![CDATA[]]></COLLINSTRUCTIONS>
</COLLECTION>
  </SENDER>
  <CONSIGNMENT><CONREF></CONREF>
<DETAILS>
 <RECEIVER></RECEIVER>
 <DELIVERY></DELIVERY>
<CUSTOMERREF><![CDATA[]]></CUSTOMERREF>
<CONTYPE><![CDATA[N]]></CONTYPE>
<PAYMENTIND><![CDATA[S]]></PAYMENTIND>
<ITEMS><![CDATA[0]]></ITEMS>
<TOTALWEIGHT><![CDATA[0]]></TOTALWEIGHT>
<TOTALVOLUME><![CDATA[0]]></TOTALVOLUME>
<CURRENCY><![CDATA[GBP]]></CURRENCY>
<GOODSVALUE><![CDATA[0]]></GOODSVALUE>
<INSURANCEVALUE><![CDATA[0]]></INSURANCEVALUE>
<INSURANCECURRENCY><![CDATA[EUR]]></INSURANCECURRENCY>
<SERVICE><![CDATA[15N]]></SERVICE>
<OPTION><![CDATA[PR]]></OPTION>
<DESCRIPTION><![CDATA[]]></DESCRIPTION>
<DELIVERYINST><![CDATA[]]></DELIVERYINST>
 <PACKAGE><ITEMS><![CDATA[0]]></ITEMS>
<DESCRIPTION><![CDATA[]]></DESCRIPTION>
<LENGTH><![CDATA[0]]></LENGTH>
<HEIGHT><![CDATA[0]]></HEIGHT>
<WIDTH><![CDATA[0]]></WIDTH>
<WEIGHT><![CDATA[0]]></WEIGHT>
<ARTICLE><ITEMS><![CDATA[0]]></ITEMS>
<DESCRIPTION><![CDATA[]]></DESCRIPTION>
<WEIGHT><![CDATA[0]]></WEIGHT>
<INVOICEVALUE><![CDATA[0]]></INVOICEVALUE>
<INVOICEDESC><![CDATA[]]></INVOICEDESC>
<HTS><![CDATA[0]]></HTS>
<COUNTRY><![CDATA[GB]]></COUNTRY>
<EMRN><![CDATA[]]></EMRN>
</ARTICLE>
</PACKAGE>
</DETAILS>
</CONSIGNMENT>
 </CONSIGNMENTBATCH>
<ACTIVITY><CREATE>
 <CONREF><![CDATA[]]></CONREF>
</CREATE>
<BOOK ShowBookingRef="Y">
 <CONREF><![CDATA[]]></CONREF>
</BOOK>
<SHIP>
 <CONREF><![CDATA[]]></CONREF>
</SHIP>
 <PRINT><CONNOTE>
 <CONREF><![CDATA[]]></CONREF>
</CONNOTE>
<LABEL>
 <CONREF><![CDATA[]]></CONREF>
</LABEL>
<MANIFEST>
 <CONREF><![CDATA[]]></CONREF>
</MANIFEST>
</PRINT>
</ACTIVITY>
</ESHIPPER>```

**Comment by 200MPH** [comment]
OK, Your request is incomplete.

Here is a minimal request you must set.
Note that sender info must match what you provided to TNT office.

$shipping->setAccountNumber('')
         ->autoActivity() // this will generate <ACTIVITY> element autmatically.
         ->setSender()->setCompanyName('')
                      ->setAddressLine('')
                      ->setCity('')
                      ->setPostcode('')
                      ->setCountry('')
                      ->setContactName('')
                      ->setContactDialCode('')
                      ->setContactPhone('')
                      ->setContactEmail('');

$shipping->setCollection()->useSenderAddress() // use same addres as is for sender
                          ->setShipDate('19/01/2018')
                          ->setPrefCollectTime('10:00', '12:00')
                          ->setCollectInstruction('');

$c1 = $shipping->addConsignment()->setConReference('')
                                 ->setCustomerRef('')
                                 ->setContype('N')
                                 ->setPaymentind('S')
                                 ->setItems(0)
                                 ->setTotalWeight(0)
                                 ->setTotalVolume(0.00)
                                 ->setService('15N')
                                 ->setDescription('')
                                 ->setDeliveryInstructions('');

$c1->setReceiver()->setCompanyName('')
                  ->setAddressLine('')
                  ->setAddressLine('')
                  ->setCity('')
                  ->setPostcode('')
                  ->setCountry('')
                  ->setContactName('')
                  ->setContactDialCode('')
                  ->setContactPhone('')
                  ->setContactEmail('');

$c1->setReceiverAsDelivery(); // make delivery address same as receiver

then 

$result = $shipping->send();

I will have a look why you do not see any errors.
Alternatively you can use TNT web form to test your request (past getXmlContent() string)
https://express.tnt.com/expresswebservices-website/app/shippingrequest.html

**Comment by Chirag-Prajapati** [comment]
HI,
I am facing the below error in sometimes so what was the issue for that.
file_get_contents(https://express.tnt.com/expressconnect/shipping/ship): failed to open stream: HTTP request failed! HTTP/1.1 500 Internal Server Error in your AbstractService.php Line: 245 
Sometimes Label is the generated proper but sometimes the label is not generated and displays this error when I remove @ from line 245 in  AbstractService.php

**Comment by 200MPH** [comment]
Hi,

You should not remove the @ against that function, this may caused
unexpected behaving when catching response. If you get 500 error from time
to time its mean problem occurs on TNT server. So your system should retry
post a shipment later.

Regards,
