### ISSUE TITLE
Invalid system dependecies

### ISSUE THREAD

**Issue by mrbig00** [200MPH/tnt#6]
Hi,

In the package.json you added php 5.6+ as a dependency, but in the MyXMLWriter::writeElementCData you typehinted some parameters with string and bool, and this is invalid for PHP < 7.

```php
public function writeElementCData(string $name, string $content = null, bool $wrap = true)
```

**Possible solutions:**

* increase php dependency 
* remove typehinting

**Comment by 200MPH** [comment]
Hi,

Thank for reporting this.
I will have a look and release hotfix.

Regards,
Wojtek

From: Szántó Zoltán
Sent: 27 July 2018 16:16
To: 200MPH/tnt
Cc: Subscribed
Subject: [200MPH/tnt] Invalid system dependecies (#6)

Hi,
In the package.json you added php 5.6+ as a dependency, but in the MyXMLWriter::writeElementCData you typehinted some parameters with string and bool, and this is invalid for PHP < 7.
public function writeElementCData(string $name, string $content = null, bool $wrap = true)
